= Current Eclipse MicroProfile Governance

Eclipse MicroProfile is a community-driven open source project made up of individuals, vendors, and organizations. Instead of a single vendor driving the project, it is the community, under the stewardship of the Eclipse Foundation, that drives it.

Eclipse MicroProfile has a bi-weekly Hangout meeting/call, which is led by the MicroProfile project leads, who currently are John Clingan (Red Hat) and Kevin Sutter (IBM). The Hangout serves as a forum where topics brought up by the community are discussed and decisions are made, from sub-project statuses and release contents, to release dates and sub-project creation approvals.

The main means of community communication, discussion and debate is the link:https://groups.google.com/forum/#!forum/microprofile[Eclipse MicroProfile Google Group]. You can use your favorite web browser to read/post/answer/start forum messages in the Google Group. You can also use the Group's link:microprofile@googlegroups.com[email] to start new forum messages. Anybody can start new forum threads to discuss topics, such as potential new functionality to be added to MicroProfile. After the community discusses a new idea at length and it's been determined that it is worth furthering the debate, the community decides to create a working sub-group and a group lead, who's usually a subject-matter expert in the topic at hand, is designated. The sub-group will establish a recurring weekly or bi-weekly meeting, which is entered in the  link:https://calendar.google.com/calendar/embed?src=gbnbc373ga40n0tvbl88nkc3r4%40group.calendar.google.com[MicroProfile Google Calendar]. Anybody can attend these meetings but there's usually a core number of people that serve as the subject-matter experts that participate in these calls. After a few meetings, the sub-group will decide whether or not the new functionality 

Eclipse MicroProfile sub-projects are (with the project leads listed):

Some of these non-Java-EE APIs may be submitted as Java Specification Requests (JSRs) for inclusion into the Java EE standard. Eclipse MicroProfile follows a time-boxed rapid incremental release schedule. Lastly, one key aspect of Eclipse MicroProfile is that it is managed and governed by the community and not a single vendor.