= Foreword

Application development no longer consists of using a single high-level programming language with a compiler that runs on your favorite operating system. Nowadays, there exists a myriad of languages, specifications, frameworks, proprietary and open source software and tools, underlying deployment infrastructures, and development methodologies programmers need to learn to develop modern applications. In this age of cloud, containers, microservices, reactive programming, 12-factor applications, serverless, miniservices, etc., a developer now has the option to choose the right tool to solve the right task.

Eclipse MicroProfile is a community-driven open-source specification for enterprise Java microservices with many implementations in the market. MicroProfile is one of the tools developers can leverage to solve problems and implement solutions designed to run enterprise applications with reliability, availability, scalability and performance (RASP) capabilities. In addition, developers familiar with enterprise Java frameworks, such as Java EE, will find in MicroProfile a natural progression of enterprise Java into the world of cloud-native application development.

With the recent move of Java EE to the Eclipse Foundation under the new name Jakarta EE, MicroProfile will play a very important role in the future of enterprise Java because of its synergy with Jakarta EE and the potential ways it can influence it.

