= What is Eclipse MicroProfile

Eclipse MicroProfile is an open source specification for Enterprise Java microservices.  It is a community-driven innovation project whose goal is to work on microservices patterns for Enterprise Java and to integrate applications with the infrastructures they run on, (that is, a cloud environment) with patterns like health checks, metrics, etc. The focus of Eclipse MicroProfile is rapid collaborative innovation and this is why the project has a time-boxed release schedule, with each release including incremental updates or new features, and there is no guarantee of backward compatibility across releases.

The Eclipse MicroProfile community is composed of individuals, vendors, and organizations.

Eclipse MicroProfile is not Java EE or a subset of Java EE. This confusion occurred because the first release of MicroProfile (before it became part of The Eclipse Foundation) was a collection of three Java EE APIs, namely, CDI, JSON-P, and JAX-RS. The MicroProfile community purposely made the first release of MicroProfile small because they wanted the community to decide the best path of evolution for the project. The MicroProfile community took a "no need to reinvent the wheel" approach for the first release and chose three enterprise-grade, market and production-proven APIs from Java EE to get started. As of the writing of this eBook, there are currently more MicroProfile-specific sub-projects within MicroProfile than Java EE APIs.

Eclipse MicroProfile 1.1 included Config, which is a MicroProfile sub-project, and Eclipse MicroProfile 1.2 included updates to Config as well as the new MicroProfile sub-projects: JWT Propagation, Metrics, Fault Tolerance, and Health Check. Likewise, Eclipse MicroProfile 1.3 included additional brand new MicroProfile sub-projects: Open API, Open Tracing, and Type-safe Rest Client. As of this writing, MicroProfile 2.0 plans to include updates to CDI, JSON-P, JAX-RS and the addition of JSON-B.