= Config

NOTE: What is the business problem that this sub-project addresses.
How does this sub-project go about addressing it.

Every application needs some external configuration to adapt its behaviour to
the running environment.
It can range from the HTTP endpoints that the application must connect to or
the size of some internal structures.

These configuration parameters can also come from different places:
* from the Operating System or the container in a Cloud-native environment (through the use of environment variables)
* from the Java Virtual Machine (with System properties)
* from some external configuration files (such as Java properties file)
* from many other places (LDAP server, Database, Key-value store, etc.)

On one hand, these configuration parameters comes from many different sources.
On the other hand, we want to consume them in the Java application in a simple
way that does not depend on the source of the configuration.

The Eclipse MicroProfile Config specification addresses this problem.

The MicroProfile Config API is split in two parts that tackles the two sides of
the problem:

* It defines `Config` and `@ConfigProperty` types that are used by the Java
application to get the values of the configuration parameters.
* It defines a SPI (Service Provider Interface) to let other projects
(or the Java application itself) provides the sources of configuration parameters.

Implementations of the MicroProfile Config must provide default `ConfigSource`
that are always available to the application.

== Reading Configuration

The MicroProfile Config specification defines two objects to read the value
of configuration parameters:

* `Config` object
* `@ConfigProperty` annotation

=== Config

The `org.eclipse.microprofile.config.Config` interface is the entry point to
 retrieve configuration in Java application.

There are two ways to get an instance of `Config`.
The first (and preferred) way is to use CDI to inject it in the code:

[source,java]
----
@Inject
private Config config; // <1>
----
<1> The config object is injected by CDI

The second way it to call the static method `org.eclipse.microprofile.config.ConfigProvider#getConfig()` to obtain
an instance of `Config`:

[source,java]
----
Config config = ConfigProvider.getConfig();
----

The `Config` interface provides two methods to retrieve properties:

* `getValue(String propertyName, Class propertyType)`
* `getOptionalValue(String propertyName, Class propertyType)`

The `getValue()` method throws an exception if the property is not present in the configuration.
This method must be used only for *mandatory* configuration (the application would not be
  able to function properly in its absence).

The `getOptionalValue()` method returns a `java.util.Optional` object that is empty if
the property is not present in the configuration. This method is used for
*optional* configuration.

Both methods will also throw exceptions if the property value, retrieved as a
`String` from the configuration, cannot be converted to the expected Java type
passed as the second argument (converters are described below).

In both methods, you need to specify the Java type you are expecting from the property.
For example, if the property corresponds to a URL, you can get its value as a `java.net.URL` directly.

[source,java]
----
URL myURL = config.getValue("my.url", URL.class);
----

The `Config` interface also defines methods to list config sources and all the properties:

* `getPropertyNames()` returns the names of the properties from all the sources
of configuration provided by the `Config` object.
* `getConfigSources()` returns all the source of configurations provided by the `Config` object

=== ConfigProperty

TODO

== Provide Sources of Configuration

The source of a configuration is represented by the `ConfigSource` interface.
You do not need to implement this interface unless you want to provide source of configurations
that are not available by the MicroProfile implementation you use in you application.

If a property is found in multiple config source, the `Config` will return the value
from the `ConfigSource` with the highest `ordinal` value.

=== Default ConfigSources

By default, a MicroProfile Config implementation must provide three source of configuration:

 * System properties from the Java Virtual Machine (with an ordinal of `400`)
 * Environment variable (with an ordinal of `300`)
 * Properties stored in a `META-INF/microprofile-config.properties` (with an ordinal of `100`)

NOTE: Their ordinal values determines the precedence of the config source. In particular, if a
property is defined both in the System properties and the Environment variables, the value
will be taken from the System properties.

There are no restriction for the names of properties. However some OS can impose
such restriction for the name of the environment variables (e.g. '.' might not be allowed).
If you have a property that could be configured from the environment variables,
you have to name your property accordingly.

For example, the property name `my_url` can be used by an environment variable while `my.url`
can not.

[TIP]
====
*New in MicroProfile Config 1.3*

MicroProfile Config 1.3 introduces an mapping rule to the
ConfigSource that provides the environment variables will then search for three
 environment variables from a single property name:

* exact match
* replace any non-alphanumeric character by `_`
* replace any non-alphanumeric character by `_` and uses upper case

This means that in the Java application, we can have a property named `app.auth.url`
and use the environment variable `APP_AUTH_URL` to configure it.
====

=== Custom ConfigSources

Explain how to define Custom ConfigSource or ConfigSourceProvider

 * Service loader + `/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource`
 * Service loader + `/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSourceProvider`

== Converters

Explains the concept of Converters

=== Built-in Converters

Describes the built-in Converters
Array converters

=== Automatic Converters

* public constructor with String parameter
* static `parse(CharSequence)` and `valueOf(String)` methods

=== Custom Converters

Explain how to define custom Converters

* Service loader + `/META-INF/services/org.eclipse.microprofile.config.spi.Converter`

=== Building your own Config

* `ConfigBuilder` SPI
* `ConfigProviderResolver.getBuilder()`

=== Summary

TODO

=== Resources

* https://github.com/eclipse/microprofile-config/releases/download/1.2/microprofile-config-spec-1.2.pdf[Eclipse MicroProfile Config 1.2 PDF Specification]
* https://github.com/eclipse/microprofile-config[Eclipse MicroProfile Config project]
