= Config

Every application needs some external configuration to adapt its behaviour to
the running environment.
It can range from the HTTP endpoints that the application must connect to or
the size of some internal structures.

These configuration parameters can also come from different places:

* from the Operating System or the container in a Cloud-native environment (through the use of environment variables)
* from the Java Virtual Machine (with System properties)
* from some external configuration files (such as Java properties file)
* from many other places (LDAP server, Database, Key-value store, etc.)

On one hand, these configuration parameters comes from many different sources.
On the other hand, we want to consume them in the Java application in a simple
way that does not depend on the source of the configuration.

The Eclipse MicroProfile Config specification addresses this problem.

The MicroProfile Config API is split in two parts that tackles the two sides of
the problem:

* It defines `Config` and `@ConfigProperty` types that are used by the Java
application to get the values of the configuration parameters.
* It defines an SPI (Service Provider Interface) to let other projects
(or the Java application itself) provides the sources of configuration parameters.

Implementations of the MicroProfile Config must provide default `ConfigSource` s
that are always available to the application.

== Reading Configuration

The MicroProfile Config specification defines two objects to read the value
of configuration parameters:

* The `Config` object to programmatically access the configuration values
* The `@ConfigProperty` annotation to inject the configuration values using CDI

=== Config

The `org.eclipse.microprofile.config.Config` interface is the entry point to
 retrieve configuration in Java application.

There are two ways to get an instance of `Config`.

. The first (and preferred) way is to use CDI to inject it in the code:
+
[source,java]
----
@Inject
private Config config; // <1>
----
+
The config object is injected by CDI.

. The second way it to call the static method `org.eclipse.microprofile.config.ConfigProvider#getConfig()` to obtain
an instance of `Config`:
+
[source,java]
----
Config config = ConfigProvider.getConfig();
----


The `Config` interface provides two methods to retrieve properties:

* `getValue(String propertyName, Class propertyType)`
* `getOptionalValue(String propertyName, Class propertyType)`

The `getValue()` method throws an exception if the property is not present in the configuration.
This method must be used only for *mandatory* configuration (the application would not be
  able to function properly in its absence).

The `getOptionalValue()` method returns a `java.util.Optional` object that is empty if
the property is not present in the configuration. This method is used for
*optional* configuration.

Both methods will also throw exceptions if the property value, retrieved as a
`String` from the configuration, cannot be converted to the expected Java type
passed as the second argument (converters are described below).

In both methods, you need to specify the Java type you are expecting from the property.
For example, if the property corresponds to a URL, you can get its value as a `java.net.URL` directly.

[source,java]
----
URL myURL = config.getValue("my.url", URL.class);
----

The `Config` interface also defines methods to list config sources and all the properties:

* `getPropertyNames()` returns the names of the properties from all the sources
of configuration provided by the `Config` object.
* `getConfigSources()` returns all the source of configurations provided by the `Config` object

=== @ConfigProperty

The `@ConfigProperty` annotation can be used to inject configuration values in Java fields or method
parameters using CDI.

[source,java]
----
@Inject
@ConfigProperty(name="my.url")
private URL myURL;
----

The `@ConfigProperty` annotation can have a `defaultValue` that is used to configure the field if
the configuration property is not found in the underlying `Config`.


[source,java]
----
@Inject
@ConfigProperty(name="my.url", defaultValue="http://localhost/")
private URL myURL;
----

If the `defaultValue` is not set and no property is found, the application will throw a DeploymentException
as it can not be properly configured.

It is possible to use `Optional` if a configuration property might not be present.

[source,java]
----
@Inject
@ConfigProperty(name="my.url")
private Optional<URL> someUrl; // will be set to Optional.empty if the
                               // property `my.url` can not be found
----


== Provide Sources of Configuration

The source of a configuration is represented by the `ConfigSource` interface.
You do not need to implement this interface unless you want to provide source of configurations
that are not available by the MicroProfile implementation you use in your application.

If a property is found in multiple config sources, the `Config` will return the value
from the `ConfigSource` with the highest `ordinal` value.

=== Default ConfigSources

By default, a MicroProfile Config implementation must provide three source of configuration:

 * System properties from the Java Virtual Machine (with an ordinal of `400`)
 * Environment variables (with an ordinal of `300`)
 * Properties stored in `META-INF/microprofile-config.properties` (with an ordinal of `100`)

NOTE: Their ordinal values determines the precedence of the config source. In particular, if a
property is defined both in the System properties and the Environment variables, the value
will be taken from the System properties.

There are no restriction for the names of properties. However some OS can impose
some restrictions for the name of the environment variables (for example, '.' might not be allowed).
If you have a property that could be configured from the environment variables,
you have to name your property accordingly.

For example, the property name `my_url` can be used by an environment variable while `my.url`
can not.

[TIP]
====
*New in MicroProfile Config 1.3*

MicroProfile Config 1.3 introduces	a mapping	rule from config property name to environment variable. This rule	searches three	environment	variable variants for each	property	name:

* exact match
* replace any non-alphanumeric character by `_`
* replace any non-alphanumeric character by `_` and uses upper case

This means that in the Java application, we can have a property named `app.auth.url`
and use the environment variable `APP_AUTH_URL` to configure it.
====

=== Custom ConfigSources

It is possible to provide additional source of configurations in your
application that will be automatically added by the MicroProfile
Config implementation.

You need to define a subclass of `org.eclipse.microprofile.config.spi.ConfigSource`
and add its name to the  `/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource`
file and put that file in your application archive.

== Converters

The MicroProfile Config will read Java `String` objects from its `ConfigSource`.
However, it provides facilities to _convert_ these Strings to more specific types in
your application.

For example, the `myUrl` field we described above is a `URL` object.
The corresponding property `my.url` is read as a `String` and then converted to a `URL` object before
it is injected.

If the application uses the `Config` object, the MicroProfile Config implementation
will also convert the `String` to the type passed as the second argument of the `getValue`
and `getOptionalValue` method.

=== Built-in Converters

The MicroProfile Config implementations provides built-in converters for the primitive types
(`boolean`, `int`, `long`, `byte`, `float`, `double`) and their corresponding Java types (for example,
  `Integer`).

It also provides support for arrays in the property value using the `,` as the item separator.
If the `,` must be part of an item, it must be escaped with a `\`.

[source,java]
----
private String[] pets = config.getValue("myPets", String[].class);
----

If the value of the property `myPets` is `dog,cat,dog\\,cat`, the elements of the array stored in
`pets` would be `{"dog", "cat", "dog,cat"}`

=== Automatic Converters

The MicroProfile Config also defines _automatic converters_. If they have no knowledge of a Converter
for a given Java type, it will attempt to convert a `String` to it using three different approaches:

* the Java type has public constructor with a `String` parameter, or
* it has a `public static valueOf(String)` method, or
* it has a `public static parse(String)` method

That's how `my.url` property was converted from a `String` to a `URL` since the `java.net.URL`
type has `public URL(String)` constructor.

=== Custom Converters

If your application defines Java types that do not provide any of these three approaches,
the MicroProfile Config can still provide conversion using custom Converters that extend the
`org.eclipse.microprofile.config.spi.Converter` interface.

[source,java]
----
public interface Converter<T> {
    /**
     * Configure the string value to a specified type
     * @param value the string representation of a property value.
     * @return the converted value or null
     *
     * @throws IllegalArgumentException if the value cannot be converted to the specified type.
     */
    T convert(String value);
}
----

You have to write a subclass of `org.eclipse.microprofile.config.spi.Converter`, add
its name to the `/META-INF/services/org.eclipse.microprofile.config.spi.Converter`
file and put that file in your application archive.

=== Summary

The Config specification provides a uniform way to configure Java applications regardless
of the deployment environment (local JVM, testing environment for continuous integration,
   container platform for production deployment, etc.).

In this chapter, we have seen how to use MicroProfile Config to configure MicroProfile applications.
The sources of the configuration can be many, some values coming from properties files,
others from System properties or environment variables but they are all accessed in
a consistent way from the Java application.
The values will likely differ according to the deployment environment (for example,
  testing and production) but that is transparent to the application code.

== Eclipse resources/GitHub coordinates for 

* https://github.com/eclipse/microprofile-config/releases/download/1.2/microprofile-config-spec-1.2.pdf[Eclipse MicroProfile Config 1.2 PDF Specification]
* https://github.com/eclipse/microprofile-config[Eclipse MicroProfile Config project]
