= Health Check

In cloud-native architectures health checks are used to determine if a computing node (i.e. your application within a container) is alive and ready to perform work. 

The concept of _readiness_ describes the state when containers startup or roll over (i.e. redeployment). During this time the cloud platform needs to ensure that no network traffic is routed to that instance before it is ready to perform work. 

_Liveness_ on the other hand, describes the state of a running container. Can it still respond to requests? Did it get stuck or did the process eventually die? If any of these states are detected, the computing node will be discarded (terminated or shutdown) and eventually replaced by another, healthy instance.

Health checks are an essential contract with the orchestration framework and scheduler of the cloud platform. The checks procedures are provided by the application (i.e. you decide how to respond to the liveness and readiness checks) and the platform uses these to continuously ensure the availability of your application or service.

== The Health Check API

Most of the plumbing is performed by the application framework that implements the Microprofile Health Check specification. Your part is do decide how liveness or readiness are expressed. 

To do this, you need to implement a Health Check procedure, like the following:

[source, java]
----
@Health
@ApplicationScoped
public class MyHealthCheck implements HealthCheck {
    @Override
    public HealthCheckResponse call() {
        return HealthCheckResponse
          .named("my-check")
          .up()
          .build();
    }
}
----

The CDI managed health checks are discovered and registered automatically my the application runtime. The runtime exposes an HTTP entry point `/health`, used by the cloud platform to poke into your application to determine it's state:

[source, json]
----
curl http://localhost:8080/health

{
    "checks": [
        {
            "name": "my-check",
            "state": "UP"
        }
    ],
    "outcome": "UP"
}
----

== Integration with the cloud platform

Most cloud-platform support both TCP and HTTP based checks. To integrate with the cloud platform simply means to configure your cloud deployment to point to the HTTP entry point `/health` on the node that hosts this application.

The cloud platform will invoke on the HTTP entry point and all checks that are registered will be invoked and the sum of individual checks determines the overall `outcome`. 

Usually the response payload is ignored by the cloud platform and it only looks at the HTTP status code to determine the liveness or readiness of your application. A successful outcome `UP` will be mapped to `200` and `DOWN` to `503`. 

== Human operators

The primary use case for the JSON response payload is to provide a way for operators to investigate the system. In support of this, health checks also allow for additional meta data to be attached to a health check response:

[source, java]
----
[...]
return HealthCheckResponse
            .named("my-check")
            .withData("free-heap", "64mb")
            .up()
            .build();
[...]
----

Here additional data ('free-heap') is provided, that will be part of the response payload:

[source,json]
----
{
    "checks": [
        {
            "name": "my-check",
            "state": "UP",
            "data": {
                "free-heap": "64mb"
            }
        }
    ],
    "outcome": "UP"
}
----



