= Health Checks

In cloud-native architectures health checks are used to determine if a computing node (i.e. your application within a container) is alive and ready to perform work. 

The concept of _readiness_ describes the state when containers startup or roll over (i.e. redeployment). During this time the cloud platform needs to ensure that no network traffic is routed to that instance before it is ready to perform work. 

_Liveness_ on the other hand, describes the state of a running container. Can it still respond to requests? Did it get stuck or did the process eventually die? If any of these states are detected, the computing node will be discarded (terminated or shutdown) and eventually replaced by another, healthy instance.

Health checks are an essential contract with the orchestration framework and scheduler of the cloud platform. The checks procedures are provided by the application (i.e. you decide how to respond to the liveness and readiness checks) and the platform uses these to continuously ensure the availability of your application or service.

== The Microprofile Health Check API


