= JWT RBAC for MicroProfile

The JWT RBAC for MicroProfile(MP-JWT) subproject outlines the requirements for using link:http://openid.net/connect/[OpenID Connect (OIDC)] based link:https://tools.ietf.org/html/rfc7519[JSON Web Tokens (JWT)] for role based access control (RBAC) of microservice endpoints.

This is done by defining which of the standard JWT claims are required, as well as introducing a two additional claims to support the RBAC functionality. 

## Recommendations for Interoperability

The maximum utility of the MP-JWT as a token format depends on the agreement between both identity providers and service providers. This means identity providers - responsible for issuing tokens - should be able to issue tokens using the MP-JWT format in a way that service providers can understand in order to introspect the token and gather information about a subject. To that end, the requirements for the MicroProfile JWT are:

1. Be usable as an authentication token.
2. Be usable as an authorization token that contains Java EE application level roles indirectly granted via a groups claim.
3. Can be mapped to IdentityStore in https://www.jcp.org/en/jsr/detail?id=375[JSR375].
4. Can support additional standard claims described in https://www.iana.org/assignments/jwt/jwt.xhtml[IANA JWT Assignments]
as well as non-standard claims.

To meet those requirements, we introduce 2 new claims to the MP-JWT:

* "upn": A human readable claim that uniquely identifies the subject or user principal of the token, across the MicroProfile services the token will be accessed with.
* "groups": The token subject's group memberships that will be mapped to Java EE style application level roles in the MicroProfile service container.

### Minimum MP-JWT Required Claims
The required minimum set of MP-JWT claims is then:

typ:: This JOSE header parameter identifies the token as an RFC7519 and must be "JWT" https://tools.ietf.org/html/rfc7519#section-5.1[RFC7519, Section 5.1]
alg:: This JOSE header parameter identifies the cryptographic algorithm used to secure the JWT. MP-JWT requires the
 use of the RSASSA-PKCS1-v1_5 SHA-256 algorithm and must be specified as "RS256", https://tools.ietf.org/html/rfc7515#section-4.1.1[RFC7515, Section 4.1.1]
kid:: This JOSE header parameter is a hint indicating which key was used to secure the JWT. https://tools.ietf.org/html/rfc7515#section-4.1.4[RFC7515, Section-4.1.4]
iss:: The MP-JWT issuer. https://tools.ietf.org/html/rfc7519#section-4.1.1[RFC7519, Section 4.1.1]
sub:: Identifies the principal that is the subject of the JWT. See the "upn" claim for how this relates to the container
 java.security.Principal. https://tools.ietf.org/html/rfc7519#section-4.1.2[RFC7519, Section 4.1.2]
exp:: Identifies the expiration time on or after which the JWT MUST NOT be accepted for processing.  The processing of the
    "exp" claim requires that the current date/time MUST be before the expiration date/time listed in the "exp" claim.
    Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew.
    Its value MUST be a number containing a NumericDate value. https://tools.ietf.org/html/rfc7519#section-4.1.4[RFC7519, Section 4.1.4]
iat:: Identifies the time at which the JWT was issued.  This claim can be used to determine the age of the JWT.  Its
    value MUST be a number containing a NumericDate value. https://tools.ietf.org/html/rfc7519#section-4.1.6[RFC7519, Section 4.1.6]
jti:: Provides a unique identifier for the JWT. The identifier value MUST be assigned in a manner that ensures that
    there is a negligible probability that the same value will be accidentally assigned to a different data object;
    if the application uses multiple issuers, collisions MUST be prevented among values produced by different issuers
    as well.  The "jti" claim can be used to prevent the JWT from being replayed.  The "jti" value is a case-sensitive string. https://tools.ietf.org/html/rfc7519#section-4.1.7[RFC7519, Section 4.1.7]
upn:: This MP-JWT custom claim is the user principal name in the java.security.Principal interface, and is the caller
    principal name in javax.security.enterprise.identitystore.IdentityStore. If this claim is missing, fallback to
    the http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims["preferred_username", OIDC Section 5.1] should be
    attempted, and if that claim is missing, fallback to the "sub" claim should be used.
groups:: This MP-JWT custom claim is the list of group names that have been assigned to the principal of the MP-JWT.
    This typically will required a mapping at the application container level to application deployment roles, but a
     one-to-one between group names and application role names is required to be performed in addition to any other mapping.

[NOTE]
NumericDate used by `exp`, `iat`, and other date related claims is a JSON numeric value
representing the number of seconds from 1970-01-01T00:00:00Z UTC until the specified
UTC date/time, ignoring leap seconds.

An example minimal MP-JWT in JSON would be:
```json
{
     "typ": "JWT",
    "alg": "RS256",
    "kid": "abc-1234567890"
}
{
       "iss": "https://server.example.com",
       "jti": "a-123",
       "exp": 1311281970,
       "iat": 1311280970,
       "sub": "24400320",
       "upn": "jdoe@server.example.com",
       "groups": ["red-group", "green-group", "admin-group", "admin"],
}
```

== High-level description of sub-project API.
The APIs the MP-JWT project introduces the following interfaces and classes under the `org.eclipse.microprofile.jwt` package namespace:

* `JsonWebToken`, a `java.security.Principal` interface extension that makes the set of required claims available via get style accessors, along with general access to any claim in the JWT.
* `Claims`, enumeration utility class encapsulates all the standard JWT related claims along with a description and the required Java type for the claim as returned from the `JsonWebToken#getClaim(String)`
method.
* `Claim`, a qualifier annotation used to signify an injection point for a {@link ClaimValue} from
* `ClaimValue<T>`, a `java.security.Principal` interface extension for use with the `Claim` qualifier to directly inject claim values from the JWT.

There is an additional `org.eclipse.microprofile.auth.LoginConfig` annotation 

=== Marking a JAX-RS Application as Requiring MP-JWT Access Control
Since the MicroProfile does not specify a deployment format, and currently does not rely on servlet metadata descriptors, we have added an `org.eclipse.microprofile.jwt.LoginConfig`
annotation that provides the same information as the `web.xml login-config` element. Its intended usage is to mark a JAX-RS `Application` as requiring MicroProfile JWT RBAC as shown in the following sample:

```java
import org.eclipse.microprofile.annotation.LoginConfig;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

@LoginConfig(authMethod = "MP-JWT", realmName = "TCK-MP-JWT")
@ApplicationPath("/")
public class TCKApplication extends Application {
}
```


== Snippets of sample code that use MP-JWT.
The basic usage of the MP-JWT API is to inject the JsonWebToken, its ClaimValues, or both. In this section we present snippets of typical usage.

=== Injection of JsonWebToken
This code sample illustrates access of the incoming MP-JWT token as a `JsonWebToken`, the raw JWT token string, and through the container `Principal`.


```java
import java.security.Principal;

import javax.annotation.security.DenyAll;
import javax.annotation.security.RolesAllowed;
import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.SecurityContext;

import org.eclipse.microprofile.jwt.Claim;
import org.eclipse.microprofile.jwt.ClaimValue;
import org.eclipse.microprofile.jwt.Claims;
import org.eclipse.microprofile.jwt.JsonWebToken;

@Path("/endp")
@DenyAll
public class JWTInjection {
    @Inject
    private JsonWebToken jwtPrincipal; // <1>
    @Inject
    @Claim(standard = Claims.raw_token)
    private ClaimValue<String> rawToken; //<2>

    @GET
    @Path("/accessInjectedToken")
    @RolesAllowed("Echoer")
    public String accessInjectedToken(@Context SecurityContext sec, @QueryParam("input") String input) {
        String name = jwtPrincipal.getName(); //<3>
        Principal user = sec.getUserPrincipal();
        assert  name.equals(user.getName()); //<4>
        return input + ", user="+user.getName();
    }

    @GET
    @Path("/accessPrinipal")
    @RolesAllowed("Echoer")
    public String accessPrincipal(@Context SecurityContext sec, @QueryParam("input") String input) {
        Principal user = sec.getUserPrincipal();
        assert user instanceof JsonWebToken; //<5>
        return input + ", user="+user.getName();
    }

}
```
<1> Direct injection of `JsonWebToken` value.
<2> Injection of the raw JWT token string. This could be used to propagate the incoming token in a chained call.
<3> Get user name from injected `JsonWebToken`.
<4> Verify that the `JsonWebToken` name claim is equal to the container provided principal name.
<5> Verify that the container provided principal is a `JsonWebToken`.

=== Injection of JWT Claim Values
The code snippet in this section illustrates injection of individual JWT claim values. There are several different formats one can use for the injected value. 



== Eclipse resources/GitHub coordinates for MP-JWT.
The MP-JWT project source code can be found at the following location: https://github.com/eclipse/microprofile-jwt-auth
