= Metrics

Metrics or telemetry exposes metric data of the running server like CPU and Memory usage, thread count and others. 
Those are then often fed into charting systems to visualize the metrics over time or serve for capacity planning purposes.

The Java Virtual machine has a way to expose data for a long time via MBeans and the MBeanServer. 
Since Java SE 6, there is even an (RMI based) remote protocol defined for all VMs on how to access the MBean Server from remote processes.

Dealing with this protocol is difficult and does not fit in today’s http-based interactions. 
The other pain point is that many of the existing servers have different properties exposed under different names. 
It is thus not easy to set up monitoring of different kinds of servers.

MicroProfile has created a monitoring specification that addresses the above two points via a http-based API for access by monitoring agents and a Java API that allows exporting application-specific metrics.

There are three scopes for metrics within the specification:

* Base: those are metrics, mostly JVM statistics, that every compliant vendor has to support.
* Vendor: optional vendor-specific metrics that are not portable.
* Application: optional metrics from deployed applications. The Java-API will be shown below.

== Metadata

One of the very important traits of MP-Metrics is Metadata.
While it is possible to expose a metric _foo_ with a value of _42_, it is not self-describing.
An operator seeing that metric can't tell what this is about, what the unit is and if 42 is good value or not.

Metadata is used to provide units and also a description of the metric so that the above could now be _foo: run time; 142 seconds_. This now allows for correct scaling on display to "2 Minutes and 22 seconds". And the user getting an alert about it can understand that this is about some run time timing.

== Retrieving metrics from the server

MicroProfile Metrics exposes metrics via a REST-interface, by default under the `/metrics` context root. With that it is easy to retrieve the data for example via the following `curl`command:

NOTE: As of MicroProfile 1.3 there is nothing in the spec about securing that endpoint. 
This is thus left to the individual implementation.

.Output in Prometheus text format (abbreviated)
[source,shell]
----
$ curl http://localhost:8080/metrics
# TYPE base:classloader_total_loaded_class_count counter
base:classloader_total_loaded_class_count 13752.0 # <1>
# TYPE base:cpu_system_load_average gauge
base:cpu_system_load_average 2.796875
# TYPE base:thread_count counter
base:thread_count 76.0
# TYPE vendor:memory_pool_metaspace_usage_max_bytes gauge # <2>
vendor:memory_pool_metaspace_usage_max_bytes 7.0916056E7
# TYPE application:hello_time_rate_per_second gauge
application:hello_time_rate_per_second{app="shop",type="timer"} 3.169298061424996E-10 # <3>
# TYPE application:hello_time_one_min_rate_per_second gauge
application:hello_time_one_min_rate_per_second{app="shop",type="timer"} 0.0
[...]
----
<1> A metric in the base scope
<2> A metric in the vendor scope
<3> A metric in the application scope

If you do not provide a media type, the default output format is the Prometheus text format (which can also nicely be rendered in the browser). 
The Prometheus format exposes additional metadata to the values in `# TYPE` and `# HELP` lines.

Alternatively it is possible to retrieve data in a Json format:

.Output in Json format (abbreviated)
[source, shell]
----
$ curl -HAccept:application/json http://localhost:8080/metrics
{
  "application" :
  {
    "gh_count" : 0,
    "doGet" : 1
  }
, "base" :
  {
    "classloader.totalLoadedClass.count" : 13970,
    "cpu.systemLoadAverage" : 2.572265625,
    "gc.PS Scavenge.time" : 290
  }
, "vendor" :
  {
    "test" : 271,
    "memoryPool.Metaspace.usage.max" : 72016928,
  }
----

In this case the pure data is exposed. Matching metadata can be retrieved via a http `OPTIONS` call:

.Retrieving metadata in Json format (abbreviated)
[source, shell]
----
$ curl XOPTIONS -HAccept:application/json http://localhost:8080/metrics
{
  "application" : {
    "helloTime": {
      "unit": "nanoseconds",
      "type": "timer",
      "description": "Timing of the Hello call",
      "tags": "app=shop,type=timer",
      "displayName": "helloTime"
    }
 }
[...]
}    
----

=== Accessing specific scopes

It is also possible to only retrieve data for a single scope by appending the scope name to the path:

.Only getting data for base scope
[source,shell]
----
$ curl http://localhost:8080/metrics/base
# TYPE base:classloader_total_loaded_class_count counter
base:classloader_total_loaded_class_count 13973.0
# TYPE base:cpu_system_load_average gauge
base:cpu_system_load_average 1.92236328125
----

It is also possible to retrieve only individual metrics by the name that is used to set the metric up, but this may go away in a future version of MicroProfile Metrics.

== Supplying application specific metrics

Applications can chose to expose metric data via a CDI programming model. 
This model follows DropWizard Metrics, so that it is easier to transition applications to MP-Metrics.
This is also using the annotations from DropWizard Metrics which have been augmented to support Metdata.

