= Open API

*What is the business problem that this sub-project addresses.
How does this sub-project go about addressing it.
High-level description of sub-project API.
Snippet(s) of sample code that implements sub-project.
Eclipse resources/GitHub coordinates for sub-project.*

The Mobile force that fuels the Digital Economy led to the necessity for businesses to establish an omni-channel approach to development in order to optimize costs, increase efficiencies and improve customer experience. This led to the API Economy and concepts such as API-led or API-first development approaches. In addition, microservices architecture has become the architecture of choice for modern development and API-based, i.e. RESTful, communication among microservices has been adopted as the de-facto standard because they are a good fit for the "smart endpoints and dumb pipes",   "decentralized governance" and "decentralized data management" characteristics of microservices. However, as the number of microservices increases in a microservices architecture, their management can become unwieldy. Microservices can be managed via their APIs. Management, security, load balancing, and throttling are policies that can be applied to APIs fronting microservices. OpenAPI provides Java interfaces and programming models which allow Java developers to natively produce OpenAPI v3 documents from their JAX-RS applications.

