= OpenTracing

In the modern world of microservices, a single request can traverse multiple processes running on different machines, datacenters or even geographical regions. The problem is often even more difficult because these services are written in different programming languages. These distributed polyglot applications are becoming gradually more difficult to understand and troubleshoot.

OpenTracing (OT) is a vendor-neutral standard for describing distributed transactions. It is a specification and a set of APIs for different programming languages. MicroProfile-OpenTracing (MP-OT) brings OpenTracing to enterprise Java environment. At the moment MP-OT specification defines tracing for JAX-RS and explicit code instrumentation.

Distributed tracing can be used for:

* Root-cause analysis
* Latency optimization -- critical path analysis
* Distributed context propagation -- baggage
* Contextual logging

=== Terminology

There are three key concepts in OpenTracing: Span, SpanContext and Tracer. Span is used to model an invoked operation in the system. It can be an internal method call or processing of a server request. A set of spans (directed acyclic graph) is called trace. Spans in the trace are related and usually model a transaction in a distributed system. Spans hold timing information, tags and logs. Identifiers are encapsulated in the object called SpanContext. The last important interface is Tracer. It is used to create spans and usually there is only one shared instance in the system.

== Configuration

OpenTracing is vendor-neutral and can, therefore, work with any vendor's tracing implementation that implements this API. Each tracer implementation will be configured differently, therefore the configuration is outside the scope of the MP-OT specification.

== Accessing Tracer

MP-OT exposes `io.opentracing.Tracer` as a CDI bean. The tracer bean can be used to create additional spans or add data (tags, logs) to the current active span. For example, this can be used for adding HTTP headers to the current server span or create an additional span to trace an important operation.

[source, java]
----
@ApplicationScoped
public class Service {

    @Inject
    private Tracer tracer;

    public void operation() {
        Span span = tracer.buildSpan("name").start();
        // some code
        span.finish();
    }    
}
----

== JAX-RS Tracing

When MP-OT implementation is enabled the container automatically traces all JAX-RS endpoints and also all outbound requests made by `javax.ws.rs.client.Client`. Therefore no custom configuration is required.

The following code snippet shows two REST endpoints. The first endpoint `/hello` creates one span modeling its execution. The second endpoint `/operation` creates two spans. The first span models server processing of HTTP request. The second span is explicitly added by user and models the invocation of the method `operation`. The second span demonstrates how users can create additional spans to model significant operations for their business or operational related monitoring.

[source, java]
----
@Path("/")
public class JaxRsService {

    @Inject
    private io.opentracing.Tracer tracer;

    @GET
    @Path("/hello")    
    public String hello() {
        return "Hello!";
    }
    
    @GET
    @Path("/operation")
    public String restOperation() {
        operation();
        return "Operation!";
    }
    
    private void operation() {
        Span span = tracer.buildSpan("operation").start();
        
        // execute some code
        
        span.finish();
    }
}
----

== Explicit Tracing

Important service classes can be explicitly traced by `@Traced` annotation. This annotation can be added at class or method level. If the annotation is applied on a class level all methods are traced. 

The annotation has two parameters:

* `traced = true` -- by default enables tracing
* `operationName = ""` -- a default operation name to override the default `<package>.<class>.<method-name>`. When overriding operation names keep in mind to use unique names for different operations. 

The annotation can be also used for JAX-RS endpoint. Typical use-case is to disable tracing for certain endpoint -- health check.

[[explicitly-traced-service]]
[source, java]
----
@Traced
@ApplicationScoped
public class Service {
    public void operation() {
        // some code
    }
    
    @Traced(false)
    public void notTracedOperation() {
        // some code
    }
    
    @Traced(operationName = "customName")
    public void renamedOperation() {
        // some code
    }
}
----

Code snippet <<explicitly-traced-service>> shows an explicitly traced class. There are two interesting things: method `notTracedOperation` is not being traced and the span modeling the invocation of `renamedOperation` method will have a string `"customName"` as  the operation name.

== Eclipse resources/GitHub coordinates for MP-OpenTracing

The MicroProfile-OpenTracing project can be found at following location:

https://github.com/eclipse/microprofile-opentracing

