= Type safe Rest Client

The Microprofile Rest Client provides an API for type-safe invocation on Rest endpoints. It can be used from applications to perform remote invocations on other services.

It leverages JAX-RS annotations on Java interfaces to describe the actual contract with remotes services. These interfaces are then used to create  client proxies that hide much of the underlying HTTP communication.  

== Rest Client API

Two concepts are central to the rest client API: The client interface used to describe the contract with a remote service and the API to construct a client proxy. Let's look at the client interface first:

[source, java]
----
import javax.json.JsonObject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

@Path("/")
public interface IPService {
    @GET
    JsonObject getIP();
}
----

This is a fairly simple contract with a remote service that echos your IP address in form of 

[source,json]
----
{"ip":"88.64.209.229"}
----

The JAX-RS annotations `@Path` and `@GET` are used to describe the actual HTTP bindings underneath. In out example an invocation to `IPService#getIP()` will be translated internally to an HTTP GET request on `/` resource of a given URL.

The client proxy for you to use, will be created using the `RestClientBuilder` which is part of the main API:

[source,java]
----
URL url = new URL("http://ip.jsontest.com/");
IPService svc = RestClientBuilder.newBuilder()
                .baseUrl(url)
                .build(IPService.class);
JsonObject response = svc.getIP();                
----

You use an URL and the client interface to construct a client proxy through `RestClientBuilder`.  The resulting instance of `IPService` can be used to invoke on the service and all HTTP communication will happen underneath.

Payload bindings to JSON-P, `javax.ws.rs.core.Response` and common simple types are supported out-of-the-box, but you can also introduce custom types if needed.

== Using custom types

The default types take you a long way, but it might be useful or needed to work with custom types. The Rest Client API, building on JAX-RS, allows to use custom types given that a `MessageBodyReader` and `MessageBodyWriter` for that type exist.

The following is an example where we explicitly create a `MessageBodyReader` for a custom type `IPService.IP`:

[source,java]
----
class IPService.IP {
    String address;

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
}
----

The corresponding reader takes the JSON payload and creates an instance of `IP`:

[source,java]
----
public class MyReader implements MessageBodyReader<IPService.IP> {
    @Override
    public boolean isReadable(Class<?> aClass, Type type, Annotation[] annotations, MediaType mediaType) {
        return true;
    }

    @Override
    public IPService.IP readFrom(
            Class<IPService.IP> aClass, Type type, Annotation[] annotations,
            MediaType mediaType, MultivaluedMap<String, String> multivaluedMap,
            InputStream inputStream) throws IOException, WebApplicationException {

        JsonReader reader = Json.createReader(inputStream);
        String ip = reader.readObject().getJsonString("ip").getString();
        IPService.IP payload = new IPService.IP();
        payload.setAddress(ip);
        return payload;
    }
}
----

To make use of that reader, we register it upon construction of the client proxy:

[source,java]
----
[...]
IPService svc = 
    RestClientBuilder.newBuilder()
	.baseUrl(url)
	.register(MyReader.class)
	.build(IPService.class);
    IPService.IP ip = svc.getIPTyped();
[...]
----


== Eclipse resources/GitHub coordinates for MP-Rest Client.
The rest client project source code can be found at the following location: https://github.com/eclipse/microprofile-rest-client

